(()=>{'use strict';
const KEY='dohwaTodoTimerV1';
const $=s=>document.querySelector(s);
const state=load(); let tickId=null,toastId=null,audioUnlocked=false;
function load(){try{const v=JSON.parse(localStorage.getItem(KEY)||'{}');return{todos:Array.isArray(v.todos)?v.todos:[],standalone:v.standalone||null};}catch(_){return{todos:[],standalone:null}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function remaining(end){return Math.max(0,Number(end||0)-Date.now())}
function fmt(ms){const sec=Math.ceil(ms/1000),m=Math.floor(sec/60),s=sec%60;return `${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function unlockAudio(){if(audioUnlocked)return;const a=$('#todo-alert-audio');if(!a)return;a.volume=0;a.play().then(()=>{a.pause();a.currentTime=0;a.volume=1;audioUnlocked=true}).catch(()=>{a.volume=1});}
function alarm(label){const a=$('#todo-alert-audio');if(a){a.volume=1;a.currentTime=0;a.play().catch(()=>{});}const t=$('#todo-alarm-toast');t.textContent=`${label||'타이머'} 시간이 끝났습니다.`;t.hidden=false;clearTimeout(toastId);toastId=setTimeout(()=>t.hidden=true,5000);}
function finishExpired(){let changed=false;state.todos.forEach(x=>{if(x.timerEnd&&!x.timerDone&&remaining(x.timerEnd)<=0){x.timerDone=true;x.timerEnd=null;alarm(x.text);changed=true;}});if(state.standalone?.end&&!state.standalone.done&&remaining(state.standalone.end)<=0){state.standalone.done=true;state.standalone.end=null;alarm(state.standalone.label||'타이머');changed=true;}if(changed)save();return changed;}
function render(){finishExpired();const list=$('#todo-list');const done=state.todos.filter(x=>x.done).length;$('#todo-progress').textContent=`완료된 할 일 : ${done}/${state.todos.length}`;list.innerHTML=state.todos.length?state.todos.map(x=>`<div class="todo-row ${x.done?'done':''}" data-id="${x.id}"><input class="todo-check" type="checkbox" ${x.done?'checked':''} aria-label="완료"><span class="todo-title" title="${esc(x.text)}">${esc(x.text)}</span><span class="todo-countdown">${x.timerEnd?fmt(remaining(x.timerEnd)):''}</span><button class="todo-icon-btn" type="button" data-action="timer" title="타이머">⏱</button><button class="todo-icon-btn" type="button" data-action="delete" title="삭제">×</button></div>`).join(''):'<div class="todo-empty">할 일을 추가해 보세요.</div>';
const s=state.standalone,active=$('#todo-active');if(s&&(s.end||s.done)){active.hidden=false;$('#todo-active-name').textContent=s.label||'타이머';$('#todo-active-time').textContent=s.end?fmt(remaining(s.end)):'00:00';}else active.hidden=true;}
function startTodoTimer(id,min){const x=state.todos.find(v=>v.id===id);if(!x)return;unlockAudio();x.timerEnd=Date.now()+min*60000;x.timerDone=false;save();render();}
function askMinutes(id){const raw=prompt('몇 분 타이머로 설정할까요?','25');if(raw===null)return;const n=Number(raw);if(Number.isFinite(n)&&n>0&&n<=1440)startTodoTimer(id,n);}
function startStandalone(min){unlockAudio();state.standalone={label:`${min}분 타이머`,end:Date.now()+min*60000,done:false};save();render();}
function init(){const dlg=$('#todo-timer-dialog');$('#menu-todo')?.addEventListener('click',()=>{dlg.hidden=false;$('#menu-todo').setAttribute('aria-expanded','true');render();});$('#todo-timer-close').addEventListener('click',()=>{dlg.hidden=true;$('#menu-todo')?.setAttribute('aria-expanded','false')});dlg.addEventListener('click',e=>{if(e.target===dlg)$('#todo-timer-close').click()});
$('#todo-add-form').addEventListener('submit',e=>{e.preventDefault();const input=$('#todo-new-input'),text=input.value.trim();if(!text)return;state.todos.push({id:uid(),text,done:false,timerEnd:null,timerDone:false});input.value='';save();render();});
$('#todo-list').addEventListener('click',e=>{const row=e.target.closest('.todo-row');if(!row)return;const x=state.todos.find(v=>v.id===row.dataset.id);if(!x)return;if(e.target.matches('.todo-check')){x.done=e.target.checked;save();render();}else if(e.target.closest('[data-action="timer"]'))askMinutes(x.id);else if(e.target.closest('[data-action="delete"]')){state.todos=state.todos.filter(v=>v.id!==x.id);save();render();}});
document.querySelectorAll('[data-todo-min]').forEach(b=>b.addEventListener('click',()=>startStandalone(Number(b.dataset.todoMin))));$('#todo-custom-start').addEventListener('click',()=>{const n=Number($('#todo-custom-minutes').value);if(Number.isFinite(n)&&n>0&&n<=1440)startStandalone(n);});$('#todo-stop').addEventListener('click',()=>{state.standalone=null;save();render();});
document.addEventListener('visibilitychange',()=>{if(!document.hidden)render();});tickId=setInterval(()=>{if(finishExpired())render();else{document.querySelectorAll('.todo-row').forEach(row=>{const x=state.todos.find(v=>v.id===row.dataset.id);const el=row.querySelector('.todo-countdown');if(el&&x?.timerEnd)el.textContent=fmt(remaining(x.timerEnd));});if(state.standalone?.end)$('#todo-active-time').textContent=fmt(remaining(state.standalone.end));}},500);render();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
